### ISSUE TITLE
PUID doesn't seem to be respected

### ISSUE THREAD

**Issue by 1n5aN1aC** [linuxserver/docker-syncthing#15]
Running on Debian, 4.9.0-3-amd64.
Docker version:   17.06.1-ce
My docker is managed with docker-compose with the config shown below.

When I define PGID & PUID in environment variables, PGUI appears to be respected, as files created have the group I asked it to use.  However, PUID does not appear to be respected, and are being created with the same ID as PGID.

In the setup below, files are being created in my /home/syncthing directory with group:998 and User:998, not the expected User:999

Relevant section of docker-compose:
```
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    restart: always
    ports:
      - "22000:22000"
      - "21027:21027/udp"
    environment:
      - PUID=999
      - PGID=998
    volumes:
      - /mnt/docker/syncthing:/config
      - /home/syncthing:/mnt/syncthing

```

Any thoughts?  Your image has been running flawlessly otherwise!
