### ISSUE TITLE
docker-syncthing should not build a volume for /sync by default

### ISSUE THREAD

**Issue by urda** [linuxserver/docker-syncthing#34]
## Expected Behavior

This image should not build a `/sync` volume. Instead, users should mount the folders they like using existing mechanisms.

## Current Behavior

This image, when deployed, will trigger a volume creation. This is not ideal in `docker-compose` environments where volumes may already be managed for specific needs. This `Dockerfile` should not be creating a volume for `/sync`. It's generated from:

https://github.com/linuxserver/docker-syncthing/blob/afe3812cdc7e362b2a93feac81f88a504cd6374e/Dockerfile#L62

If this `/sync` is removed (such as a forked `Dockerfile` as I did locally), this "issue" goes away.

## Steps to Reproduce

1. Pull `syncthing:v1.3.0-ls19` and use the image.
2. Notice a new volume is created.
3. Check `Dockerfile` source to figure out why, find out why.

## Environment
**OS:** N/A
**CPU architecture:** N/A      
**How docker service was installed:** `portainer` normally, but manual testing for issue reporting. Applies to both.

## Command used to create docker container (run/create/compose/screenshot)
Compose details:

```yaml
version: "2"
services:
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - TZ=UTC
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    volumes:
      - /path/to/syncthing/config:/config
      - /path/to/syncthing/data:/syncthing/data
    restart: unless-stopped
```
