### ISSUE TITLE
cannot get to gui on windows

### ISSUE THREAD

**Issue by dzmitry-lahoda** [linuxserver/docker-syncthing#35]
public GUI is not accessible on windows:
```
---
version: "2"
services:
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=<022>
    volumes:
      - E:/src/peer/storage/config/config:/config
      - E:/src/peer/storage/lahoda.pro/laptop:/lahoda.pro/laptop
      - E:/src/peer/storage/lahoda.pro/mobile:/lahoda.pro/mobile
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
```

```
docker-compose --file ./docker-compose.yml run syncthing
```
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
./run: line 5: umask: `<': invalid symbolic mode operator
[start] 08:28:44 INFO: syncthing v1.3.2 "Fermium Flea" (go1.12.12 linux-amd64) root@1047530fbeb1 2019-12-03 07:36:37 UTC
[services.d] done.
[TZFUF] 08:28:44 INFO: My ID: TZFUF2M-3MDAJN6-WHM3BYG-GWW2HRZ-EVDJAOW-OLPYMER-ENIPGDS-75HJPQ5
[TZFUF] 08:28:44 INFO: Single thread SHA256 performance is 377 MB/s using minio/sha256-simd (332 MB/s using crypto/sha256).
[TZFUF] 08:28:45 INFO: Hashing performance is 303.82 MB/s
[TZFUF] 08:28:45 INFO: Ready to synchronize "Default Folder" (default) (sendreceive)
[TZFUF] 08:28:45 INFO: Overall send rate is unlimited, receive rate is unlimited
[TZFUF] 08:28:45 INFO: Using discovery server https://discovery.syncthing.net/v2/?noannounce&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[TZFUF] 08:28:45 INFO: Using discovery server https://discovery-v4.syncthing.net/v2/?nolookup&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[TZFUF] 08:28:45 INFO: Using discovery server https://discovery-v6.syncthing.net/v2/?nolookup&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[TZFUF] 08:28:45 INFO: QUIC listener ([::]:22000) starting
[TZFUF] 08:28:45 INFO: TCP listener ([::]:22000) starting
[TZFUF] 08:28:45 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[TZFUF] 08:28:45 INFO: Completed initial scan of sendreceive folder "Default Folder" (default)
[TZFUF] 08:28:45 INFO: GUI and API listening on [::]:8384
[TZFUF] 08:28:45 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[TZFUF] 08:28:45 INFO: My name is "84361aa4cf5b"
[TZFUF] 08:28:56 INFO: quic://0.0.0.0:22000 detected NAT type: Symmetric NAT
[TZFUF] 08:28:56 INFO: quic://0.0.0.0:22000 resolved external address quic://37.215.190.146:64497 (via stun.syncthing.net:3478)
[TZFUF] 08:29:06 INFO: Detected 1 NAT service
[TZFUF] 08:29:15 INFO: Joined relay relay://94.16.114.88:22067
```
```
PS E:\src\peer\storage> curl http://127.0.0.1:8384/
curl: (7) Failed to connect to 127.0.0.1 port 8384: Connection refused
```

I expect to get to GUI, but fail. I have tested running nginx

```
docker run -p 12312:80 -d nginx
PS C:\Users\dzmitry> curl http://127.0.0.1:12312
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

```
