### ISSUE TITLE
1.20.3 fails with s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by hansij66** [linuxserver/docker-syncthing#58]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Image got updated to latest (1.20.3) and fails with
syncthing    | s6-overlay-suexec: fatal: can only run as pid 1

1.20.2 (and older) are fine.

------------------------------

## Expected Behavior

Container should start (as it does with 1.20.2)

## Current Behavior

Update to 1.20.3
Start with docker-compose:
syncthing    | s6-overlay-suexec: fatal: can only run as pid 1

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**
Debian; Linux hans-svr 5.10.0-16-amd64 #1 SMP Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux
**CPU architecture:** x86_64
**How docker service was installed:**
official docker repo; latest docker-ce

## Command used to create docker container (run/create/compose/screenshot)

```
---
version: "3"
services:
  syncthing:
    container_name: ${TAG}
    image: lscr.io/linuxserver/syncthing:1.20.2
    hostname: hans-svr

    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Amsterdam

    volumes:
    - /home/hans/programming/git:/data3
    - ./data/config:/config

    expose:
    - 8384

    ports:
    - 192.168.1.1:8384:8384
    - 192.168.1.1:22000:22000/tcp
    - 192.168.1.1:22000:22000/udp

    restart: unless-stopped

    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.${TAG}.entrypoints=web-https"
    - "traefik.http.routers.${TAG}.rule=Host(`www.example.com`) && PathPrefix(`/${TAG}`)"
    - "traefik.http.routers.${TAG}.tls.certResolver=letsencrypt"
    - "traefik.http.services.${TAG}.loadbalancer.server.port=8384"
    - "traefik.http.services.${TAG}.loadbalancer.server.scheme=https"

    - "traefik.http.routers.${TAG}.middlewares=${TAG}-chain"
    - "traefik.http.middlewares.${TAG}-stripprefix.stripprefix.prefixes=/${TAG}"
    - "traefik.http.middlewares.${TAG}-chain.chain.middlewares=authelia@docker, ${TAG}-stripprefix"

    networks:
    - frontend

networks:
  frontend:
    external:
      name: traefik-proxy
```

## Docker logs

syncthing    | s6-overlay-suexec: fatal: can only run as pid 1
